### ISSUE TITLE
Bug when training collection2collection model

### ISSUE THREAD

**Issue by mauryaland** [AlekseyKorshuk/huggingnft#2] opened 2022-07-02 16:21 UTC
Hello,

First of all thanks for this project, funny way to discover GANs !

When launching the training for the collection2collection model from the CLI, I have the following error:

```python
Reusing dataset parquet (C:\Users\33667\.cache\huggingface\datasets\maurya___parquet\maurya--gc-d26997f7b4f4065f\0.0.0\7328ef7ee03eaf3f86ae40594d46a1cec86161704e02dd19f232d81eee72ade8)
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.90it/s]
Using custom data configuration maurya--gc-d26997f7b4f4065f
Reusing dataset parquet (C:\Users\33667\.cache\huggingface\datasets\maurya___parquet\maurya--gc-d26997f7b4f4065f\0.0.0\7328ef7ee03eaf3f86ae40594d46a1cec86161704e02dd19f232d81eee72ade8)
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.97it/s]
Starting training
Traceback (most recent call last):
  File "C:\Users\33667\Documents\huggingnft\huggingnft\cyclegan\train.py", line 470, in <module>
    main()
  File "C:\Users\33667\Documents\huggingnft\huggingnft\cyclegan\train.py", line 466, in main
    training_function({}, args)
  File "C:\Users\33667\Documents\huggingnft\huggingnft\cyclegan\train.py", line 225, in training_function
    for i, (source_batch, target_batch) in enumerate(zip(loaders['train']['source'], loaders['train']['target']) ):
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\accelerate\data_loader.py", line 301, in __iter__
    for batch in super().__iter__():
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\torch\utils\data\dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\torch\utils\data\dataloader.py", line 1048, in __init__
    w.start()
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'training_function.<locals>.transforms'
Traceback (most recent call last):
  File "C:\Users\33667\anaconda3\envs\nft\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\33667\anaconda3\envs\nft\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\33667\anaconda3\envs\nft\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\accelerate\commands\launch.py", line 568, in launch_command
    simple_launcher(args)
  File "C:\Users\33667\anaconda3\envs\nft\lib\site-packages\accelerate\commands\launch.py", line 250, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\33667\\anaconda3\\envs\\nft\\python.exe', 'train.py', '--batch_size', '8', '--beta1', '0.5', '--beta2', '0.999', '--channels', '3', '--checkpoint_interval', '5', '--decay_epoch', '80', '--epoch', '0', '--image_size', '256', '--lambda_cyc', '10.0', '--lambda_id', '5.0', '--lr', '0.0002', '--mixed_precision', 'no', '--n_residual_blocks', '9', '--num_epochs', '200', '--num_workers', '8', '--sample_interval', '10', '--source_dataset_name', 'maurya/gc', '--target_dataset_name', 'maurya/gc', '--output_dir', 'experiments']' returned non-zero exit status 1.
(nft) PS C:\Users\33667\Documents\huggingnft\huggingnft\cyclegan> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\33667\anaconda3\envs\nft\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

The traceback is unclear and I can't debug it. I tried also with your datasets and get the same issue. Running the lightweight gan works perfectly.

Thanks in advance for your answer.

**Comment by mauryaland** [comment] 2022-07-03 13:50
Setting num_workers=0 fix the issue. Found the  solution here https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/1197

**Comment by AlekseyKorshuk** [comment] 2022-07-03 20:15
Hello, sorry for long reply. Does upper message solve the issue completely?

Guess I need to cc @Chris1nexus

**Comment by mauryaland** [comment] 2022-07-03 20:38
No worries! Thanks for the reply.

Upper message solved the issue indeed. I migrated training on colab because my GPU was not good enough and the problem does not appear anymore.

**Comment by AlekseyKorshuk** [comment] 2022-07-03 20:40
Awesome 🤗
I am closing this issue. Feel free to reopen it if needed 👌

**Closed as completed** 2022-07-03 20:41 UTC

**Comment by Chris1nexus** [comment] 2022-07-04 14:29
@mauryaland The issue is caused by the use of parallel dataloading on a Windows platform(as i can see that you are developing on Win from the paths shown in the stack trace).
Pytorch always had this issue in its past versions and the only way to solve it is to set num_workers=0 for each dataloader(if you are using a windows system). 

There are many other weird interactions between pytorch and windows that are sort of known online (e.g. https://github.com/pytorch/pytorch/issues/51344), but you should have no such bugs by running pytorch based code on linux systems

**Comment by mauryaland** [comment] 2022-07-04 14:49
Thanks for the clear explanation @Chris1nexus 👍
